package com.globot.hmi.attendance.domain;

import java.util.Date;

public class EmployeeRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_role.id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_role.employee_id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    private Integer employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_role.role_id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_role.add_time
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_role.modify_time
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_role.mome
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    private String mome;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_role.id
     *
     * @return the value of employee_role.id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_role.id
     *
     * @param id the value for employee_role.id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_role.employee_id
     *
     * @return the value of employee_role.employee_id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_role.employee_id
     *
     * @param employeeId the value for employee_role.employee_id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_role.role_id
     *
     * @return the value of employee_role.role_id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_role.role_id
     *
     * @param roleId the value for employee_role.role_id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_role.add_time
     *
     * @return the value of employee_role.add_time
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_role.add_time
     *
     * @param addTime the value for employee_role.add_time
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_role.modify_time
     *
     * @return the value of employee_role.modify_time
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_role.modify_time
     *
     * @param modifyTime the value for employee_role.modify_time
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_role.mome
     *
     * @return the value of employee_role.mome
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public String getMome() {
        return mome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_role.mome
     *
     * @param mome the value for employee_role.mome
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public void setMome(String mome) {
        this.mome = mome == null ? null : mome.trim();
    }
}