package com.globot.hmi.attendance.domain;

import java.io.Serializable;
import java.util.Date;

public class Resource  implements Serializable, Comparable<Resource> {
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.name
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.url
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.add_time
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.modify_time
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.status
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.display
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    private Boolean display;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.mome
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    private String mome;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.name
     *
     * @return the value of resource.name
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.name
     *
     * @param name the value for resource.name
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.url
     *
     * @return the value of resource.url
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.url
     *
     * @param url the value for resource.url
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.add_time
     *
     * @return the value of resource.add_time
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.add_time
     *
     * @param addTime the value for resource.add_time
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.modify_time
     *
     * @return the value of resource.modify_time
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.modify_time
     *
     * @param modifyTime the value for resource.modify_time
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.status
     *
     * @return the value of resource.status
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.status
     *
     * @param status the value for resource.status
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.display
     *
     * @return the value of resource.display
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public Boolean getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.display
     *
     * @param display the value for resource.display
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public void setDisplay(Boolean display) {
        this.display = display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.mome
     *
     * @return the value of resource.mome
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public String getMome() {
        return mome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.mome
     *
     * @param mome the value for resource.mome
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public void setMome(String mome) {
        this.mome = mome == null ? null : mome.trim();
    }

        public int compareTo(Resource other)
        {
            if(this.id < other.id)
                return -1;
            if(this.id > other.id)
                return 1;
            return 0;
        }
}