package com.globot.hmi.attendance.domain;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.add_time
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.modify_time
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.status
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.mome
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    private String mome;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.add_time
     *
     * @return the value of role.add_time
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.add_time
     *
     * @param addTime the value for role.add_time
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.modify_time
     *
     * @return the value of role.modify_time
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.modify_time
     *
     * @param modifyTime the value for role.modify_time
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.status
     *
     * @return the value of role.status
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.status
     *
     * @param status the value for role.status
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.mome
     *
     * @return the value of role.mome
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public String getMome() {
        return mome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.mome
     *
     * @param mome the value for role.mome
     *
     * @mbggenerated Sun Nov 19 16:28:02 CST 2017
     */
    public void setMome(String mome) {
        this.mome = mome == null ? null : mome.trim();
    }
}