package com.globot.hmi.attendance.domain;

import java.util.Date;

public class RoleResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.role_id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.resource_id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    private Integer resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.add_time
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.modify_time
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.mome
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    private String mome;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.id
     *
     * @return the value of role_resource.id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.id
     *
     * @param id the value for role_resource.id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.role_id
     *
     * @return the value of role_resource.role_id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.role_id
     *
     * @param roleId the value for role_resource.role_id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.resource_id
     *
     * @return the value of role_resource.resource_id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.resource_id
     *
     * @param resourceId the value for role_resource.resource_id
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.add_time
     *
     * @return the value of role_resource.add_time
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.add_time
     *
     * @param addTime the value for role_resource.add_time
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.modify_time
     *
     * @return the value of role_resource.modify_time
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.modify_time
     *
     * @param modifyTime the value for role_resource.modify_time
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.mome
     *
     * @return the value of role_resource.mome
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public String getMome() {
        return mome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.mome
     *
     * @param mome the value for role_resource.mome
     *
     * @mbggenerated Sun Nov 19 17:06:02 CST 2017
     */
    public void setMome(String mome) {
        this.mome = mome == null ? null : mome.trim();
    }
}